# PyMarkdownLnt configuration
# Documentation: https://github.com/jackdewinter/pymarkdown

# Disable rules that are too strict for this project
plugins:
  # MD013: Line length - 80 chars is too restrictive for modern displays
  line-length:
    enabled: false

  # MD022: Blank lines around headings - less strict for existing docs
  blanks-around-headings:
    enabled: false

  # MD031: Blank lines around fenced code blocks - less strict
  blanks-around-fences:
    enabled: false

  # MD036: Emphasis as heading - less strict for existing docs
  no-emphasis-as-heading:
    enabled: false

  # MD034: Bare URLs - common in documentation
  no-bare-urls:
    enabled: false

  # MD024: Duplicate headings - common in structured docs
  no-duplicate-heading:
    enabled: false

  # MD035: Horizontal rule style - less important
  hr-style:
    enabled: false

# Global configuration
mode:
  strict: false
