name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      run: uv python install 3.12

    - name: Install dependencies
      run: uv sync --all-extras --dev

    - name: Code Quality Checks
      run: |
        echo "Running all quality checks..."

        echo "1. Ruff linting..."
        uv run ruff check . || exit 1

        echo "2. Ruff formatting..."
        uv run ruff format --check . || exit 1

        echo "3. MyPy type checking..."
        uv run mypy chemscreen/ || exit 1

        echo "4. Markdown linting..."
        uv run pymarkdownlnt scan **/*.md || exit 1

        echo "5. Running tests..."
        uv run pytest || exit 1

        echo "✅ All checks passed!"

  check-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Verify lock file is up to date
      run: |
        uv lock --check
        echo "✅ Lock file is up to date"
