[theme]
primaryColor = "#0066CC"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 10
enableCORS = true
enableXsrfProtection = true
enableWebsocketCompression = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501
